import itertools
import math
import pytest

from optionsengine import (IVStatus, SolverConfig, bsm_price, forward_intrinsic, implied_volatility,
                           upper_bound)

S, K, T, R, Q = 100.0, 100.0, 0.5, 0.05, 0.01


def iv(price, ot="call", S=S, K=K, T=T, r=R, q=Q, cfg=SolverConfig()):
    return implied_volatility(price, S, K, T, r, q, ot, cfg)


GRID = list(itertools.product([100.0], [70.0, 90.0, 100.0, 115.0, 150.0], [1 / 365, 7 / 365, 0.25, 2.0],
                              [-0.01, 0.05, 0.10], [0.0, 0.03], [0.05, 0.15, 0.4, 1.2], ["call", "put"]))


@pytest.mark.parametrize("S,K,T,r,q,sigma,ot", GRID[::3])
def test_recovers_known_vol(S, K, T, r, q, sigma, ot):
    price = bsm_price(S, K, T, r, q, sigma, ot)
    res = implied_volatility(price, S, K, T, r, q, ot)
    if res.converged:
        # accuracy guaranteed by the stated criterion: |dsigma| <= price_tol / vega
        bound = max(res.diagnostics.vol_uncertainty * 2, 1e-9)
        assert abs(res.iv - sigma) <= bound
        if not res.diagnostics.ill_conditioned:
            assert abs(res.iv - sigma) < 1e-6
        cfg = SolverConfig()
        assert abs(bsm_price(S, K, T, r, q, res.iv, ot) - price) <= min(cfg.price_tol, cfg.price_rel_tol * price)
        assert res.kind == "market_implied"
    else:
        # the ONLY acceptable failures are explicit "price carries no vol info" statuses
        # (e.g. the theoretical price underflowed to exactly 0.0), and they must come with iv=None.
        assert res.iv is None
        assert res.status in (IVStatus.PRICE_NOT_POSITIVE, IVStatus.AT_BOUND, IVStatus.OUTSIDE_VOL_RANGE, IVStatus.BELOW_LOWER_BOUND,
                              IVStatus.NOT_CONVERGED), res.status


def test_well_conditioned_region_always_converges_accurately():
    for sigma in (0.05, 0.1, 0.2, 0.35, 0.6, 1.0):
        for K_ in (90, 100, 110):
            for ot in ("call", "put"):
                p = bsm_price(S, K_, T, R, Q, sigma, ot)
                res = iv(p, ot, K=K_)
                assert res.converged and not res.diagnostics.ill_conditioned
                assert res.iv == pytest.approx(sigma, abs=1e-8)


def test_call_and_put_at_same_strike_give_same_iv():
    sigma = 0.27
    c = iv(bsm_price(S, 105, T, R, Q, sigma, "call"), "call", K=105)
    p = iv(bsm_price(S, 105, T, R, Q, sigma, "put"), "put", K=105)
    assert c.iv == pytest.approx(p.iv, abs=1e-8)


@pytest.mark.parametrize("r,q", [(0.0, 0.0), (0.10, 0.0), (0.05, 0.05), (0.02, 0.08), (-0.01, 0.0)])
def test_different_rates_and_yields(r, q):
    p = bsm_price(S, 95, 0.75, r, q, 0.22, "put")
    res = iv(p, "put", K=95, T=0.75, r=r, q=q)
    assert res.converged and res.iv == pytest.approx(0.22, abs=1e-8)


def test_same_price_different_rate_gives_different_iv():
    p = bsm_price(S, 110, 1.0, 0.05, 0.0, 0.2, "call")
    a = iv(p, K=110, T=1.0, r=0.05, q=0.0).iv
    b = iv(p, K=110, T=1.0, r=0.09, q=0.0).iv
    assert a != pytest.approx(b, abs=1e-4)  # the assumption genuinely matters


# ---- invalid / unreliable prices: never a seemingly valid IV ----------------
@pytest.mark.parametrize("price,status", [
    (0.0, IVStatus.PRICE_NOT_POSITIVE), (-1.0, IVStatus.PRICE_NOT_POSITIVE),
    (float("nan"), IVStatus.INVALID_INPUT), (float("inf"), IVStatus.INVALID_INPUT),
    (None, IVStatus.INVALID_INPUT), ("5", IVStatus.INVALID_INPUT),
])
def test_bad_prices(price, status):
    res = iv(price)
    assert res.status is status and res.iv is None and not res.converged


def test_below_lower_bound_call_and_put():
    lb = forward_intrinsic(S, 80, T, R, Q, "call")
    res = iv(lb - 0.5, K=80)
    assert res.status is IVStatus.BELOW_LOWER_BOUND and res.iv is None
    lbp = forward_intrinsic(S, 120, T, R, Q, "put")
    res = iv(lbp - 0.5, "put", K=120)
    assert res.status is IVStatus.BELOW_LOWER_BOUND and res.iv is None


def test_above_upper_bound():
    res = iv(upper_bound(S, K, T, R, Q, "call") + 0.01)
    assert res.status is IVStatus.ABOVE_UPPER_BOUND and res.iv is None
    res = iv(K * math.exp(-R * T) + 0.01, "put")
    assert res.status is IVStatus.ABOVE_UPPER_BOUND and res.iv is None


def test_price_barely_above_intrinsic_is_flagged_ill_conditioned():
    lb = forward_intrinsic(S, 80, T, R, Q, "call")
    res = iv(lb + 1e-7, K=80)
    assert (res.converged and res.diagnostics.ill_conditioned) or res.iv is None


def test_price_exactly_on_bound_is_not_identifiable():
    res = iv(forward_intrinsic(S, 80, T, R, Q, "call"), K=80)
    assert res.status is IVStatus.AT_BOUND and res.iv is None


def test_price_implying_vol_outside_range():
    # ATM price generated by a 0.001% vol: root is far below vol_min (0.01%).
    Katm = S * math.exp((R - Q) * T)  # ATM forward, so price is pure time value
    res = iv(bsm_price(S, Katm, T, R, Q, 1e-5, "call"), K=Katm)
    assert res.status is IVStatus.OUTSIDE_VOL_RANGE and res.iv is None
    # Huge price: root above vol_max (500%).
    ub = upper_bound(S, K, T, R, Q, "call")
    res = iv(ub * 0.999999, K=K)
    assert res.status in (IVStatus.OUTSIDE_VOL_RANGE, IVStatus.AT_BOUND) and res.iv is None


def test_expired_and_invalid_inputs_are_reported_not_raised():
    assert iv(5.0, T=0.0).status is IVStatus.EXPIRED
    assert iv(5.0, T=-1.0).status is IVStatus.INVALID_INPUT
    assert iv(5.0, S=0).status is IVStatus.INVALID_INPUT
    assert iv(5.0, K=-1).status is IVStatus.INVALID_INPUT
    assert iv(5.0, ot="straddle").status is IVStatus.INVALID_INPUT
    assert iv(5.0, r=float("nan")).status is IVStatus.INVALID_INPUT
    assert iv(5.0, T=0.0).iv is None


def test_solver_convergence_failure_returns_no_iv():
    p = bsm_price(S, 140, 0.5, R, Q, 0.9, "call")
    res = iv(p, K=140, cfg=SolverConfig(max_iter=1, price_tol=1e-14))
    assert res.status is IVStatus.NOT_CONVERGED
    assert res.iv is None and not res.converged
    assert "NOT a valid IV" in res.diagnostics.message
    assert res.diagnostics.iterations == 1


def test_tight_tolerance_that_cannot_be_met_fails_loudly():
    # below float resolution of the price itself -> must not claim convergence
    p = bsm_price(S, K, T, R, Q, 0.2, "call")
    res = iv(p, cfg=SolverConfig(price_tol=1e-300, max_iter=60))
    assert res.status in (IVStatus.NOT_CONVERGED, IVStatus.CONVERGED)
    if res.status is IVStatus.CONVERGED:
        assert abs(res.diagnostics.price_error) <= 1e-300
    else:
        assert res.iv is None


def test_deep_otm_ill_conditioned_is_flagged():
    sigma = 0.15
    p = bsm_price(24500, 28000, 3 / 365, 0.065, 0.0, sigma, "call")
    res = implied_volatility(p, 24500, 28000, 3 / 365, 0.065, 0.0, "call")
    if res.converged:
        assert res.diagnostics.ill_conditioned or abs(res.iv - sigma) < 1e-6
    else:
        assert res.iv is None


def test_deep_itm_roundtrip_or_explicit_failure():
    p = bsm_price(100, 30, 1.0, 0.05, 0.0, 0.2, "call")
    res = implied_volatility(p, 100, 30, 1.0, 0.05, 0.0, "call")
    assert (res.converged and abs(bsm_price(100, 30, 1.0, 0.05, 0.0, res.iv, "call") - p) <= 1e-8) or res.iv is None


@pytest.mark.parametrize("T_", [1e-6, 1e-5, 1 / 365 / 24 / 60, 1 / 365])
def test_near_expiry_atm_recovery(T_):
    p = bsm_price(100, 100, T_, 0.05, 0.0, 0.3, "call")
    res = implied_volatility(p, 100, 100, T_, 0.05, 0.0, "call")
    assert res.converged and res.iv == pytest.approx(0.3, abs=1e-6)


def test_near_expiry_otm_does_not_fake_vol():
    p = bsm_price(100, 105, 1e-6, 0.05, 0.0, 0.3, "call")  # price underflows to 0
    res = implied_volatility(p, 100, 105, 1e-6, 0.05, 0.0, "call")
    assert not res.converged and res.iv is None


def test_diagnostics_populated_on_success():
    p = bsm_price(S, K, T, R, Q, 0.25, "call")
    d = iv(p).diagnostics
    assert d.iterations >= 1 and d.vega_raw > 0 and d.bracket and d.lower_bound is not None
    assert abs(d.price_error) <= min(SolverConfig().price_tol, SolverConfig().price_rel_tol * p)


def test_solver_config_validation():
    with pytest.raises(Exception):
        SolverConfig(vol_min=1.0, vol_max=0.5)
    with pytest.raises(Exception):
        SolverConfig(price_tol=0)
