"""Stage 2D Gate 3c (T12): claim ledger, consolidated final report, language lint. No new statistics: reads committed Gate 1-3b CSVs only."""
import argparse
import glob
import hashlib
import json
import os
import subprocess
from datetime import datetime
from typing import List

import pandas as pd

from . import claim_lint as L, claims as K

PROTOCOL = "PROSPECTIVE_PROTOCOL.md"
REPORTS = ["gate1/REPORT.md", "gate1/IMPLEMENTATION_PLAN.md", "gate2/REPORT.md", "gate2/PREREGISTRATION.md", "gate2/IMPLEMENTATION_PLAN.md", "gate3/REPORT_3A.md", "gate3/GATE3A_IMPLEMENTATION_PLAN.md",
           "gate3/REPORT_3B.md", "gate3/GATE3B_IMPLEMENTATION_PLAN.md", "gate3/GATE3C_IMPLEMENTATION_PLAN.md", "gate3/" + PROTOCOL]


def sha(path: str) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def _git() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def ledger_frame(claims: List[K.Claim], tier1_s, tier1_r) -> pd.DataFrame:
    rows = []
    for c in claims:
        chk = tier1_s if "S1" in c.estimands and c.claim_id == "C01" else tier1_r if c.claim_id == "C03" else None
        rows.append(dict(claim_id=c.claim_id, topic=c.topic, status=c.status, evidence_tier=c.tier, tier_meaning=K.TIERS[c.tier], claim=c.claim, key_numbers=c.key_numbers, sources=c.sources, required_warnings=c.warnings,
                         allowed_wording=c.allowed, forbidden_wording=c.forbidden, estimands=";".join(c.estimands), interval_based=c.interval_based, t11_undercoverage_warning_attached=c.undercoverage_warning,
                         tier1_conditions=("" if chk is None else ";".join(f"{k}={v}" for k, v in chk.items()))))
    return pd.DataFrame(rows)


def ledger_markdown(df: pd.DataFrame) -> str:
    out = ["# Stage 2D claim ledger", "", "Generated by `build_gate3c.py` from the committed Gate 1-3b CSVs; every number is read from those files. Status vocabulary and tiers: see `FINAL_REPORT.md`.", ""]
    for _, r in df.iterrows():
        out += [f"## {r.claim_id} — {r.topic}", f"**Status:** {r.status} · **Evidence tier:** {r.evidence_tier} ({r.tier_meaning})", "", f"**Claim.** {r.claim}", "", f"**Numbers.** {r.key_numbers}", "",
                f"**Required warnings.** {r.required_warnings}", "", f"**Allowed wording.** {r.allowed_wording}", "", f"**Forbidden wording.** {r.forbidden_wording}", "", f"**Sources.** {r.sources}", ""]
        if r.tier1_conditions:
            out += [f"**Tier 1 conditions checked.** {r.tier1_conditions}", ""]
    return "\n".join(out) + "\n"


def final_report(df: pd.DataFrame, s: K.Src, lint_counts: dict) -> str:
    t = K.t11_numbers(s)
    cov = s.df("gate3/t11b_coverage.csv")
    piv = cov.groupby(["scenario", "method"]).coverage.mean().unstack().round(3)
    cov_tab = ["| scenario | " + " | ".join(piv.columns) + " |", "|---|" + "---|" * len(piv.columns)]
    for sc, r in piv.iterrows():
        cov_tab.append(f"| {sc} | " + " | ".join(f"{v:.3f}" for v in r.values) + " |")
    head = ["| id | topic | status | tier | key numbers | T11 warning |", "|---|---|---|---|---|---|"]
    for _, r in df.iterrows():
        ests = str(r.estimands).split(";") if isinstance(r.estimands, str) and r.estimands else []
        if r.interval_based and any(e in ("R1", "R1e", "R2", "R2e", "R3") for e in ests):
            w = f"RATIO INTERVAL UNDER-COVERS: {t['rlo']:.1%}-{t['rhi']:.1%} synthetic coverage (nominal 95%); worse under strong dependence"
        elif r.interval_based:
            w = f"spread-median synthetic coverage {t['slo']:.1%}-{t['shi']:.1%}; not transferable to real data"
        else:
            w = "-"
        head.append(f"| {r.claim_id} | {r.topic} | {r.status} | {r.evidence_tier} | {r.key_numbers} | {w} |")
    n_stat = df.status.value_counts().to_dict()
    L_ = [
        "# Stage 2D — consolidated final report (T12)", "",
        "Status: **measurement and statistics only.** No trading strategy, entry/exit rule, P&L, signal, sizing, threshold optimisation or Fyers integration exists in Stage 2D. "
        "This report is generated from the committed Gate 1–3b tables by `build_gate3c.py`; it adds no statistic. Not committed, not pushed.", "",
        "> **Headline reading.** The historical sample shows implied volatility above subsequently realised volatility, with intervals that are probably too narrow for the ratio estimands (T11). "
        "Whether any of this is tradable is not assessable with this dataset (no bid/ask, costs, margin or execution information), and nothing has been tested on expiries after 2026-09-30.", "",
        "## 1. Evidence tiers and statuses",
        "* **Tier 0** — descriptive association in this sample. **Tier 1** — statistical evidence: the expiry-block interval excludes the null, dev and holdout lie on the same side of it, every expiry year and every tested specification do too, and T9 detects no outcome-dependent selection (all five conditions are computed and stored in the ledger). **Tier 2** — tradable edge: not assessable here.",
        "* Statuses: SUPPORTED_WITH_CAVEATS, SUPPORTED_METHOD (about the statistical procedures), INCONCLUSIVE, NOT_SUPPORTED, NOT_ASSESSABLE, NOT_CLAIMED. "
        f"Counts: " + ", ".join(f"{k} {v}" for k, v in sorted(n_stat.items())) + ".", "",
        "## 2. Claim ledger (summary; full wording, warnings and forbidden phrases in `claim_ledger.md` / `claim_ledger.csv`)", *head, "",
        "## 3. The T11 finding (preserved, not tuned away)",
        "Tier A (small full-pipeline known-truth recovery) is a successful pipeline-recovery validation (claim C14). Tier B (calibrated synthetic coverage/dependence study, 300 histories of 260 expiries per scenario) is evidence that the current "
        "percentile-bootstrap uncertainty procedure does **not** achieve nominal 95% coverage uniformly:",
        f"* spread-median estimands reached {t['slo']:.1%}–{t['shi']:.1%} in the calibrated scenario with expiry blocks of length 5;",
        f"* ratio estimands reached only {t['rlo']:.1%}–{t['rhi']:.1%} there, so **every ratio interval in Stage 2D carries an explicit under-coverage warning**;",
        f"* the strong-dependence stress scenario was materially worse (best method {t['b1lo']:.0%}–{t['b1hi']:.0%});",
        f"* row-level i.i.d. inference covered only {t['row_lo']:.0%}–{t['row_hi']:.0%} and is invalid for this dependent, overlapping structure;",
        "* these percentages are properties of a calibrated simulation and must not be extrapolated directly to the real dataset. The simulation is less clustered (ICC 0.49 vs 0.575 observed) but more serially dependent (ACF(1) 0.275 vs 0.128), has less negative skew and more rows per expiry; "
        "18 of 27 calibration moments fall inside the simulated 5–95% range.", "",
        "Mean coverage over the nine estimands (nominal 95%):", "", *cov_tab, "",
        "## 4. What each gate contributed",
        "* **Gate 1 (T1–T4):** expiry as the independence unit, block bootstrap for overlapping weekly windows, dependence diagnostics, ratio inference, influence analysis.",
        "* **Gate 2 (T5–T8):** dev-vs-holdout contrasts (holdout previously viewed), pre-registered heterogeneity tests with Holm, a convention/filter specification curve, and the forking-paths ledger.",
        "* **Gate 3a (T9–T10):** selection audit of rejected observations (information known at t only), Manski bounds and IPW; bid/ask-free quote-noise scenarios, labelled assumptions and bounds.",
        "* **Gate 3b (T11):** pipeline recovery on synthetic worlds and the calibrated coverage study above.",
        "* **Gate 3c (T12):** this ledger, the language lint and the frozen prospective protocol.", "",
        "## 5. What is not claimed",
        "No variance risk premium, no mispricing, no tradability, no profitability, no out-of-sample confirmation (the holdout was displayed in Stage 2C and Gate 1), no prospective validation, and no statement about maturities beyond 14 days (claims C11, C18–C20).", "",
        "## 6. Limitations carried by every claim",
        "Last-trade prices only (no bid/ask); a same-direction bias of roughly the size in C12 would explain the whole spread and cannot be tested here; percentile intervals from 260 expiries; the ≤ 14 DTE universe; "
        "common pipeline assumptions shared by every specification; the synthetic coverage study's calibration gaps; Tier B coverage SE about 1.3 points.", "",
        "## 7. Prospective test", "A frozen protocol (`PROSPECTIVE_PROTOCOL.md`, hash in `run_metadata_3c.json`) applies the unchanged pipeline to expiries after 2026-09-30, requires at least 52 expiries, reports b = 5 and b = 8, "
        "and fixes the wording of the outcome. No prospective result exists.", "",
        "## 8. Language lint (`lint_report.csv`)", f"Ledger, final report and protocol: {lint_counts['new_flags']} flags. Committed Gate 1–3b documents (frozen, not edited): {lint_counts['old_flags']} flagged sentences, "
        f"{lint_counts['old_ok']} negated/limited uses. Each flagged sentence is listed with its file and line.", "",
        "## 9. Reproduction",
        "```", "python -m optionsengine.research.stage2d.build_gate3c --out research_output/stage2d/gate3", "python research_output/stage2d/gate3/validation/independent_gate3c_check.py", "python -m pytest -q", "```", ""]
    return "\n".join(L_)


def build(root: str, out: str) -> dict:
    if "stage2d" not in os.path.normpath(out).split(os.sep):
        raise ValueError("Stage 2D outputs must live under a 'stage2d' directory")
    os.makedirs(out, exist_ok=True)
    s = K.Src(root)
    claims = K.build_claims(s)
    t1s, t1r = K.tier1_checks(s, True), K.tier1_checks(s, False)
    bad = L.check_ledger(claims, {**t1s})
    if bad:
        raise ValueError("claim ledger violates its own rules: " + "; ".join(bad))
    df = ledger_frame(claims, t1s, t1r)
    df.to_csv(os.path.join(out, "claim_ledger.csv"), index=False)
    with open(os.path.join(out, "claim_ledger.md"), "w", encoding="utf-8") as f:
        f.write(ledger_markdown(df))
    # report (lint counts need a first pass over the generated text)
    old = [os.path.join(root, p) for p in REPORTS if os.path.exists(os.path.join(root, p))]
    old = [p for p in old if not p.endswith(("GATE3C_IMPLEMENTATION_PLAN.md", PROTOCOL))] if False else old
    rep = final_report(df, s, dict(new_flags=0, old_flags=0, old_ok=0))
    findings = []
    findings += L.lint_text(rep, "FINAL_REPORT.md")
    findings += L.lint_text(ledger_markdown(df), "claim_ledger.md")
    findings += L.lint_files(old)
    new = [f for f in findings if f["source"] in ("FINAL_REPORT.md", "claim_ledger.md") or f["source"].endswith((PROTOCOL, "GATE3C_IMPLEMENTATION_PLAN.md"))]
    oldf = [f for f in findings if f not in new]
    counts = dict(new_flags=sum(f["status"] == "FLAG" for f in new), old_flags=sum(f["status"] == "FLAG" for f in oldf), old_ok=sum(f["status"] == "NEGATED_OK" for f in oldf))
    rep = final_report(df, s, counts)
    with open(os.path.join(out, "FINAL_REPORT.md"), "w", encoding="utf-8") as f:
        f.write(rep)
    pd.DataFrame(findings).to_csv(os.path.join(out, "lint_report.csv"), index=False)
    meta = dict(git_commit=_git(), n_claims=len(df), statuses=df.status.value_counts().to_dict(), lint=counts, protocol_sha256=sha(os.path.join(out, PROTOCOL)) if os.path.exists(os.path.join(out, PROTOCOL)) else None,
                source_hashes={p: sha(p) for p in sorted(glob.glob(os.path.join(root, "gate*", "*.csv")))}, generated=datetime.now().isoformat(timespec="seconds"), plan="GATE3C_IMPLEMENTATION_PLAN.md")
    with open(os.path.join(out, "run_metadata_3c.json"), "w") as f:
        json.dump(meta, f, indent=1)
    return meta


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="research_output/stage2d")
    ap.add_argument("--out", default="research_output/stage2d/gate3")
    a = ap.parse_args(argv)
    m = build(a.root, a.out)
    print(json.dumps({k: v for k, v in m.items() if k != "source_hashes"}, indent=1))


if __name__ == "__main__":
    main()
